# Generated by Django 5.0.6 on 2026-06-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Men", "Homme"),
                    ("Women", "Femme"),
                    ("Boys", "Garçon"),
                    ("Girls", "Fille"),
                ],
                max_length=10,
                verbose_name="Genre",
            ),
        ),
    ]
